# Start from a clean Python image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install scirpy
RUN pip install --no-cache-dir scirpy==0.17.2

# https://github.com/scverse/scirpy?tab=readme-ov-file