LABEL maintainer="Chris Tastad <christopher.tastad@mssm.edu>"



# Start from a clean Python image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install cellphonedb v5.0.1
RUN pip install --no-cache-dir cellphonedb==5.0.1
